// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace albumbackend.Migrations
{
    [DbContext(typeof(AlbumFigurinhasContext))]
    [Migration("20180916140538_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Models.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Models.Figurinha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AlbumId");

                    b.Property<string>("ImgUrl");

                    b.Property<long>("NumeroFigurinha");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Figurinhas");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<long?>("MeuAlbumId");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.HasIndex("MeuAlbumId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Models.Figurinha", b =>
                {
                    b.HasOne("Models.Album")
                        .WithMany("MinhasFigurinhas")
                        .HasForeignKey("AlbumId");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.HasOne("Models.Album", "MeuAlbum")
                        .WithMany()
                        .HasForeignKey("MeuAlbumId");
                });
#pragma warning restore 612, 618
        }
    }
}
